# Generated by Django 4.1.7 on 2023-04-01 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sekil', models.ImageField(upload_to='images/', verbose_name='Sekil')),
                ('name', models.CharField(max_length=255, verbose_name='Ad')),
                ('metn', models.TextField(verbose_name='metn')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaranma tarixi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yaradan')),
            ],
        ),
    ]
