# Generated by Django 4.1.7 on 2023-03-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_article_create_date_article_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='metn',
            field=models.TextField(default='', verbose_name='metn'),
            preserve_default=False,
        ),
    ]
