# Generated by Django 4.1.7 on 2023-04-01 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_article_metn'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sekil',
            field=models.ImageField(default=datetime.datetime(2023, 4, 1, 6, 18, 13, 628726, tzinfo=datetime.timezone.utc), upload_to='images/', verbose_name='Foto'),
            preserve_default=False,
        ),
    ]
